--
-- PostgreSQL database dump
--

\restrict y6DKXq9aa6wesYnGOQ13mbZ2vcrGYdZ47YYgNSOTonajhTzo96cd7jDCEHtkgwL

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-05-27 13:50:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS flores_nuria;
--
-- TOC entry 5117 (class 1262 OID 16437)
-- Name: flores_nuria; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE flores_nuria WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Spain.1252';


ALTER DATABASE flores_nuria OWNER TO postgres;

\unrestrict y6DKXq9aa6wesYnGOQ13mbZ2vcrGYdZ47YYgNSOTonajhTzo96cd7jDCEHtkgwL
\connect flores_nuria
\restrict y6DKXq9aa6wesYnGOQ13mbZ2vcrGYdZ47YYgNSOTonajhTzo96cd7jDCEHtkgwL

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 916 (class 1247 OID 17102)
-- Name: tipo_producto; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.tipo_producto AS ENUM (
    'flor',
    'planta',
    'accesorio',
    'pack'
);


ALTER TYPE public.tipo_producto OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 238 (class 1259 OID 17090)
-- Name: accesorios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accesorios (
    producto_id integer NOT NULL,
    material character varying(50),
    "tamaño" character varying(50)
);


ALTER TABLE public.accesorios OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16921)
-- Name: categorias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias (
    id_categoria integer NOT NULL,
    nombre character varying
);


ALTER TABLE public.categorias OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16969)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id_cliente integer NOT NULL,
    nombre character varying,
    mail character varying,
    telefono integer,
    correo character varying(255)
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16961)
-- Name: empleado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empleado (
    id_empleado integer NOT NULL,
    puesto character varying,
    nombre character varying,
    telefono integer,
    correo character varying,
    password character varying
);


ALTER TABLE public.empleado OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 17067)
-- Name: flores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.flores (
    producto_id integer NOT NULL,
    color character varying(50),
    especie character varying(100),
    fecha_corte date
);


ALTER TABLE public.flores OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17043)
-- Name: oferta_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oferta_producto (
    id_oferta integer NOT NULL,
    id_producto integer NOT NULL
);


ALTER TABLE public.oferta_producto OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16905)
-- Name: ofertas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ofertas (
    id_oferta integer NOT NULL,
    nombre character varying,
    descuento double precision,
    "fechaFin" date,
    fecha_creacion date,
    fecha_actualizacion date,
    activa boolean DEFAULT true
);


ALTER TABLE public.ofertas OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17041)
-- Name: ofertas_id_oferta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ofertas ALTER COLUMN id_oferta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ofertas_id_oferta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16945)
-- Name: pack; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pack (
    id_pack integer NOT NULL,
    "nombrePack" character varying NOT NULL,
    "precioPack" double precision NOT NULL
);


ALTER TABLE public.pack OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16983)
-- Name: pedido_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedido_producto (
    id_pedido_producto integer NOT NULL,
    id_producto integer,
    id_pedido integer,
    cantidad integer
);


ALTER TABLE public.pedido_producto OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17038)
-- Name: pedido_producto_id_pedido_producto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedido_producto ALTER COLUMN id_pedido_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_producto_id_pedido_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16929)
-- Name: pedidos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedidos (
    id_pedido integer NOT NULL,
    "fechaPedido" date,
    estado character varying,
    id_proveedor integer,
    total_pedido double precision
);


ALTER TABLE public.pedidos OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 17037)
-- Name: pedidos_id_pedido_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedidos ALTER COLUMN id_pedido ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_id_pedido_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 17078)
-- Name: plantas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plantas (
    producto_id integer NOT NULL,
    frecuencia_riego character varying(100),
    es_exterior boolean DEFAULT false,
    tipo_sustrato character varying(100)
);


ALTER TABLE public.plantas OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16913)
-- Name: producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto (
    id_producto integer NOT NULL,
    nombre character varying,
    "precioBase" double precision,
    stock integer,
    id_categoria integer,
    iva numeric(5,2) DEFAULT 21.00,
    categoria public.tipo_producto
);


ALTER TABLE public.producto OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 17035)
-- Name: producto_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16937)
-- Name: proveedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proveedor (
    id_proveedor integer NOT NULL,
    nombre character varying,
    telefono integer,
    direccion character varying,
    correo character varying
);


ALTER TABLE public.proveedor OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17036)
-- Name: proveedor_id_proveedor_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.proveedor ALTER COLUMN id_proveedor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedor_id_proveedor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16955)
-- Name: venta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venta (
    id_venta integer NOT NULL,
    precio double precision,
    fecha date,
    num_venta integer,
    id_cliente integer,
    id_empleado integer
);


ALTER TABLE public.venta OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16977)
-- Name: venta_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venta_producto (
    id_venta_producto integer NOT NULL,
    id_venta integer,
    id_producto integer,
    cantidad integer
);


ALTER TABLE public.venta_producto OWNER TO postgres;

--
-- TOC entry 4951 (class 2606 OID 17095)
-- Name: accesorios accesorios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accesorios
    ADD CONSTRAINT accesorios_pkey PRIMARY KEY (producto_id);


--
-- TOC entry 4947 (class 2606 OID 17072)
-- Name: flores flores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flores
    ADD CONSTRAINT flores_pkey PRIMARY KEY (producto_id);


--
-- TOC entry 4927 (class 2606 OID 16928)
-- Name: categorias id_categoria; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT id_categoria PRIMARY KEY (id_categoria);


--
-- TOC entry 4939 (class 2606 OID 16976)
-- Name: cliente id_cliente; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT id_cliente PRIMARY KEY (id_cliente);


--
-- TOC entry 4937 (class 2606 OID 16968)
-- Name: empleado id_empleado; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT id_empleado PRIMARY KEY (id_empleado);


--
-- TOC entry 4923 (class 2606 OID 16912)
-- Name: ofertas id_ofertas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ofertas
    ADD CONSTRAINT id_ofertas PRIMARY KEY (id_oferta);


--
-- TOC entry 4933 (class 2606 OID 16954)
-- Name: pack id_pack; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pack
    ADD CONSTRAINT id_pack PRIMARY KEY (id_pack);


--
-- TOC entry 4929 (class 2606 OID 16936)
-- Name: pedidos id_pedido; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT id_pedido PRIMARY KEY (id_pedido);


--
-- TOC entry 4925 (class 2606 OID 16920)
-- Name: producto id_producto; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT id_producto PRIMARY KEY (id_producto);


--
-- TOC entry 4931 (class 2606 OID 16944)
-- Name: proveedor id_proveedor; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedor
    ADD CONSTRAINT id_proveedor PRIMARY KEY (id_proveedor);


--
-- TOC entry 4935 (class 2606 OID 16960)
-- Name: venta id_venta; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta
    ADD CONSTRAINT id_venta PRIMARY KEY (id_venta);


--
-- TOC entry 4943 (class 2606 OID 16988)
-- Name: pedido_producto pedido_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_producto
    ADD CONSTRAINT pedido_producto_pkey PRIMARY KEY (id_pedido_producto);


--
-- TOC entry 4945 (class 2606 OID 17049)
-- Name: oferta_producto pk_oferta_producto; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oferta_producto
    ADD CONSTRAINT pk_oferta_producto PRIMARY KEY (id_oferta, id_producto);


--
-- TOC entry 4949 (class 2606 OID 17084)
-- Name: plantas plantas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plantas
    ADD CONSTRAINT plantas_pkey PRIMARY KEY (producto_id);


--
-- TOC entry 4941 (class 2606 OID 16982)
-- Name: venta_producto venta_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta_producto
    ADD CONSTRAINT venta_producto_pkey PRIMARY KEY (id_venta_producto);


--
-- TOC entry 4964 (class 2606 OID 17096)
-- Name: accesorios accesorios_producto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accesorios
    ADD CONSTRAINT accesorios_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.producto(id_producto) ON DELETE CASCADE;


--
-- TOC entry 4960 (class 2606 OID 17050)
-- Name: oferta_producto fk_oferta; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oferta_producto
    ADD CONSTRAINT fk_oferta FOREIGN KEY (id_oferta) REFERENCES public.ofertas(id_oferta) ON DELETE CASCADE;


--
-- TOC entry 4961 (class 2606 OID 17055)
-- Name: oferta_producto fk_producto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oferta_producto
    ADD CONSTRAINT fk_producto FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto) ON DELETE CASCADE;


--
-- TOC entry 4962 (class 2606 OID 17073)
-- Name: flores flores_producto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flores
    ADD CONSTRAINT flores_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.producto(id_producto) ON DELETE CASCADE;


--
-- TOC entry 4952 (class 2606 OID 16994)
-- Name: producto id_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT id_categoria FOREIGN KEY (id_categoria) REFERENCES public.categorias(id_categoria) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4954 (class 2606 OID 17004)
-- Name: venta id_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta
    ADD CONSTRAINT id_cliente FOREIGN KEY (id_cliente) REFERENCES public.cliente(id_cliente) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4955 (class 2606 OID 17009)
-- Name: venta id_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta
    ADD CONSTRAINT id_empleado FOREIGN KEY (id_empleado) REFERENCES public.empleado(id_empleado) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4958 (class 2606 OID 17024)
-- Name: pedido_producto id_pedido; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_producto
    ADD CONSTRAINT id_pedido FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id_pedido) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4959 (class 2606 OID 17029)
-- Name: pedido_producto id_producto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_producto
    ADD CONSTRAINT id_producto FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4956 (class 2606 OID 17014)
-- Name: venta_producto id_producto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta_producto
    ADD CONSTRAINT id_producto FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4953 (class 2606 OID 16999)
-- Name: pedidos id_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT id_proveedor FOREIGN KEY (id_proveedor) REFERENCES public.proveedor(id_proveedor) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4957 (class 2606 OID 17019)
-- Name: venta_producto id_venta; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta_producto
    ADD CONSTRAINT id_venta FOREIGN KEY (id_venta) REFERENCES public.venta(id_venta) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4963 (class 2606 OID 17085)
-- Name: plantas plantas_producto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plantas
    ADD CONSTRAINT plantas_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.producto(id_producto) ON DELETE CASCADE;


-- Completed on 2026-05-27 13:50:39

--
-- PostgreSQL database dump complete
--

\unrestrict y6DKXq9aa6wesYnGOQ13mbZ2vcrGYdZ47YYgNSOTonajhTzo96cd7jDCEHtkgwL

