-- Script de actualización de la base de datos "floresnuria"
-- Este script añade las columnas necesarias para que las clases PHP funcionen correctamente.

-- 1. Actualizar tabla empleado
ALTER TABLE public.empleado ADD COLUMN IF NOT EXISTS telefono integer;
ALTER TABLE public.empleado ADD COLUMN IF NOT EXISTS correo character varying;
ALTER TABLE public.empleado ADD COLUMN IF NOT EXISTS password character varying;

-- Asignar una contraseña temporal ('123456') a los empleados actuales para que puedan iniciar sesión
UPDATE public.empleado SET password = '$2y$10$RAS7xD1qk4SJ6w7IDfhSR.zbH6yjwCP4zznXMVrVaD05KFsXmr7M2' WHERE password IS NULL;

-- 2. Actualizar tabla proveedor
-- Renombrar columna "nombreEmpresa" a "nombre"
ALTER TABLE public.proveedor RENAME COLUMN "nombreEmpresa" TO nombre;
ALTER TABLE public.proveedor ADD COLUMN IF NOT EXISTS direccion character varying;
ALTER TABLE public.proveedor ADD COLUMN IF NOT EXISTS correo character varying;

-- 3. Actualizar tabla ofertas
ALTER TABLE public.ofertas ADD COLUMN IF NOT EXISTS fecha_creacion date;
ALTER TABLE public.ofertas ADD COLUMN IF NOT EXISTS fecha_actualizacion date;

-- 4. Actualizar tabla pedidos
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS total_pedido double precision;

-- 5. Actualizar tabla pedido_producto
ALTER TABLE public.pedido_producto ADD COLUMN IF NOT EXISTS cantidad integer;

-- 6. Actualizar tabla venta_producto
-- Renombrar "cantidad_producto" a "cantidad" para que coincida con las clases y con pedido_producto
ALTER TABLE public.venta_producto RENAME COLUMN cantidad_producto TO cantidad;

-- 7. Hacer que los IDs sean autoincrementales (Identity Columns)
-- Esto soluciona el error de "Not null violation" al hacer INSERT sin especificar un ID
ALTER TABLE public.producto ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.proveedor ALTER COLUMN id_proveedor ADD GENERATED BY DEFAULT AS IDENTITY;


-- 8. A�adir IVA a producto
ALTER TABLE public.producto ADD COLUMN IF NOT EXISTS iva numeric(5,2) DEFAULT 21.00;


-- 9. Solucionar id_oferta nulo en tabla ofertas
ALTER TABLE public.ofertas ALTER COLUMN id_oferta ADD GENERATED BY DEFAULT AS IDENTITY;


-- 10. M�ltiples productos por oferta
CREATE TABLE IF NOT EXISTS public.oferta_producto (id_oferta integer NOT NULL, id_producto integer NOT NULL, CONSTRAINT pk_oferta_producto PRIMARY KEY (id_oferta, id_producto), CONSTRAINT fk_oferta FOREIGN KEY (id_oferta) REFERENCES public.ofertas (id_oferta) ON DELETE CASCADE, CONSTRAINT fk_producto FOREIGN KEY (id_producto) REFERENCES public.producto (id_producto) ON DELETE CASCADE);
ALTER TABLE public.ofertas DROP COLUMN IF EXISTS id_producto;

